CREATE TABLE IF NOT EXISTS `book` (
	`id` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`titulo` VARCHAR(255) NOT NULL,
	`autor` VARCHAR(255) NULL DEFAULT NULL,
	`data_lancamento` DATETIME(6) NULL DEFAULT NULL,
	`preco` DOUBLE NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
