name: Continuous Integration with Github Actions

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./05_firstJava/java-spring-boot
      run: mvn clean package -DskipTests

    - name: Docker Composer Build
      working-directory: ./05_firstJava
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/java-spring-boot:latest ${{ secrets.DOCKER_USERNAME }}/java-spring-boot:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/java-spring-boot:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/java-spring-boot:latest
